---
apiVersion: v1
kind: Pod
metadata:
  name: tenant-workload-uses-host-path
  namespace: tenant
spec:
  hostNetwork: true
  containers:
    - image: nginx:stable
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 100m
          memory: 100Mi
  volumes:
    - hostPath:
        path: "/"
