---
apiVersion: v1
kind: Pod
metadata:
  name: tenant-workload-uses-host-port
  namespace: tenant
spec:
  containers:
    - image: nginx:stable
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
          hostPort: 443
      resources:
        requests:
          cpu: 50m
          memory: 50Mi
        limits:
          cpu: 100m
          memory: 100Mi
