apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: require-node-selection
  namespace: tenant
spec:
  validationFailureAction: enforce
  rules:
  - name: require-tolerations-be-set
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: If a tenant opts to have their own node group, all of their workloads must be scheduled on the node group.
      deny:
        conditions:
          any:
            - key: '{{ request.object.spec.tolerations  || `[]` | length(@) }}'
              operator: LessThan
              value: 1
  - name: require-node-selector
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: If a tenant opts to have their own node group, all of their workloads must be scheduled on the node group.
      pattern:
        spec:
          nodeSelector:
            tenant: "true"
  - name: require-correct-toleration-be-set
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: If a tenant opts to have their own node group, all of their workloads must be scheduled on the node group.
      pattern:
        spec:
          ^(tolerations):
          - effect: NoSchedule
            key: reserved
            operator: Equal
            value: tenant
