---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  endpointSelector:
    matchLabels:
      app: {{ .Values.name }}     
  ingress:
    # TODO make this configurable, so we can restrict to specific pods
    - fromEndpoints:
        - {}
    {{- if or .Values.privateIngressEnabled .Values.publicIngressEnabled }}    
    - fromEndpoints:
        {{- if .Values.privateIngressEnabled }}
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": traefik-private
            "app.kubernetes.io/instance": traefik-private-traefik-private
        {{- end }}
        {{- if .Values.publicIngressEnabled }}
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": traefik-public
            "app.kubernetes.io/instance": traefik-public-traefik-public
        {{- end }}
    {{- end }}
  egress:
    # allow egress to any pod in this namespace, all other namespaces are denied
    # TODO make this configurable, so we can restrict to specific pods
    - toEndpoints:
        - {}
    # allow egress to the internet
    # note we don't allow to the `world` entity, because technically that will allow 10.x.x.x, which
    # means we could call anything in k8s using IP because of how the EKS CNI works.
    # TODO make this configurable, so it can be disabled.
    - toCIDRSet:
        - cidr: 0.0.0.0/0
          except:
            # https://en.wikipedia.org/wiki/Reserved_IP_addresses
            - 0.0.0.0/8
            - 10.0.0.0/8
            - 100.64.0.0/10
            - 169.254.0.0/16
            - 172.16.0.0/12
            - 192.0.0.0/24
            - 192.0.2.0/24
            - 192.88.99.0/24
            - 192.168.0.0/16
            - 198.18.0.0/15
            - 198.51.100.0/24
            - 203.0.113.0/24
            - 224.0.0.0/4
            - 233.252.0.0/24
            - 240.0.0.0/4
            - 255.255.255.255/32
