---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.tenantName }}-developer-access
  namespace: {{ .Values.tenantName }}
subjects:
  - kind: Group
    name: eks-{{ .Values.tenantName }}-developers
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ .Values.tenantName }}-developer-access
  apiGroup: rbac.authorization.k8s.io
