# TODO disable the admin user and use OIDC for access to argocd
# configs:
#   cm:
#     admin.enabled: false

# TODO network policies may not be applied to argocd
redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  replicas: 2

repoServer:
  replicas: 2

applicationSet:
  replicaCount: 2

tolerations:
  - key: "node.cilium.io/agent-not-ready"
    value: "true"

config:
  cm: annotation+label
