# TODO disable the admin user and use OIDC for access to argocd
# configs:
#   cm:
#     admin.enabled: false

# TODO network policies may not be applied to argocd
redis-ha:
  enabled: true

controller:
  replicas: 1

server:
  replicas: 2

repoServer:
  replicas: 2

applicationSet:
  replicaCount: 2

tolerations:
  - key: "node.cilium.io/agent-not-ready"
    value: "true"

configs:
  cm:
    # this needs to be overridden so as not to clash with kyverno (https://argo-cd.readthedocs.io/en/latest/user-guide/resource_tracking/#choosing-a-tracking-method)
    application.resourceTrackingMethod: annotation+label
    # disables status field diffing in specified resource types (https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#ignoring-rbac-changes-made-by-aggregateroles)
    resource.compareoptions.ignoreAggregatedRoles: true
